name: Build and Deploy Innowarmth.com

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build Astro site
        run: bun run build

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
            server: ${{ secrets.ftp_host }}
            username: ${{ secrets.ftp_username }}
            password: ${{ secrets.ftp_password }}
            port: ${{ secrets.ftp_port }}
            protocol: ftps
            local-dir: ./dist
            server-dir: //home/innowag/www # Change this to your target directory
            dry-run: false